name: "Build and Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '35 19 * * 4'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        targetplatform: [ x86, x64 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #- name: Setup dotnet
    #  uses: actions/setup-dotnet@v2
    #  with:
    #    dotnet-version: '6.0.x'
    #    include-prerelease: true

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Install workloads
      run: |
        dotnet workload install maui
        dotnet workload install wasm-tools

    #- name: Build Maui
    #  run: dotnet build ./samples/MauiSample

    #- name: Build Uno.UWP
    #  run: msbuild ./samples/UnoSample/UnoSample.UWP /t:Restore

    #- name: Build Uno.Wasm
    #  run: msbuild ./samples/UnoSample/UnoSample.Wasm /t:Restore

    #- name: Build Uno.Wpf.Host
    #  run: msbuild ./samples/UnoSample/UnoSample.Wpf.Host /t:Restore

    #- name: Build Uno.Skia.Gtk
    #  run: msbuild ./samples/UnoSample/UnoSample.Skia.Gtk /t:Restore

    # locally I get an error to build uno mobile using msbuild:
    # error M564086: A numeric comparison was attempted on "g_CurrentTrimmedAndroidSOLVersiony that evaluates to "" instead of a number, in condition $(_CurrentTrimmedA ndroidSDLVersion)' < '$(UnoUIMinAndroidSDKVersion)".
    # - name: Build Uno.Mobile
    #   run: msbuild ./samples/UnoSample/UnoSample.Mobile /t:Restore

    - name: Build Avalonia
      run: dotnet build ./samples/AvaloniaSample

    - name: Build Blazor
      run: dotnet build ./samples/BlazorSample

    - name: Build WinForms
      run: dotnet build ./samples/WinFormsSample

    - name: Build WPF
      run: dotnet build ./samples/WPFSample

    - name: Build Xamarin
      run: dotnet build ./samples/XamarinSample/XamarinSample/XamarinSample

    - name: Build EtoForms
      run: dotnet build ./samples/EtoFormsSample

    - name: Build WinUI
      run: msbuild ./samples/WinUISample/WinUI/WinUI/WinUISample.csproj /t:Restore

    - name: Run unit tests
      run: dotnet test ./tests/LiveChartsCore.UnitTesting
