name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Install dependencies
      run: dotnet restore ./src/LiveChartsCore
      
    - name: Build
      run: dotnet build ./src/LiveChartsCore --configuration Release --no-restore

    - name: Publish LiveChartsCore
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/LiveChartsCore/LiveChartsCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true

    - name: Publish LiveChartsCore.SkiaSharpView
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp/LiveChartsCore.SkiaSharpView.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
          
    - name: Publish LiveChartsCore.SkiaSharpView.Avalonia
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/LiveChartsCore.SkiaSharpView.Avalonia.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
          
    - name: Publish LiveChartsCore.SkiaSharpView.WinForms
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp.WinForms/LiveChartsCore.SkiaSharpView.WinForms.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
          
    - name: Publish LiveChartsCore.SkiaSharpView.WPF
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp.WPF/LiveChartsCore.SkiaSharpView.WPF.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
          
    - name: Publish LiveChartsCore.SkiaSharpView.XamarinForms
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/skiasharp/LiveChartsCore.SkiaSharp.Xamarin.Forms/LiveChartsCore.SkiaSharpView.Xamarin.Forms.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
